name: game
version: '1.0-SNAPSHOT'
main: org.ant.plugin.Game
api-version: '1.21.4'
authors: [ Antonio111 ]
description: Ant development

permissions:
  antgame.command:
    antgame:
      description: 允許玩家使用 /antgame 指令
      default: op