name: AntGame
version: "1.0-SNAPSHOT"
main: org.ant.game.Game
api-version: "1.21.4"
authors: [ Antonio111 ]
description: Ant development
dependencies:
  server:
    MCKotlin-Paper:
      required: true
