name: AntGame
version: "1.0"
main: org.ant.plugin.Game
api-version: "1.21.4"
authors: [ Antonio111 ]
description: Ant development

permissions:
  antgame.command:
    game_operate:
      description: 允許玩家使用 /antgame game_operate 指令
      default: op
    save_config:
      description: 允許玩家使用 /antgame save_config 指令
      default: op
