name: AntGame
version: "3.0.1"
main: org.ant.game.AntGamePlugin
api-version: "1.21.8"
authors: [ Antonio111 ]
description: Ant development

depend: [MCKotlin-Paper]

permissions:
  antgame.command:
      description: 允許玩家使用 /antgame 指令
      default: op
